# Generated by Django 3.0.11 on 2021-04-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ParentName', max_length=200)),
                ('modified', models.DateTimeField(db_column='Modified_on')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testngdj.Student')),
            ],
        ),
    ]
