# Generated by Django 3.0.3 on 2021-04-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testngdj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='modified',
        ),
        migrations.AddField(
            model_name='parent',
            name='age',
            field=models.CharField(db_column='Age', default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='nothing@gmail.com', max_length=250),
            preserve_default=False,
        ),
    ]
